spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER}
    password: ${PGPASS}
    url: ${DATABASE}
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false
appId: ${APPID}
appSecret: ${APPSECRET}
server:
  port: ${PORT:8080}