spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PG_PACYORKY_USER}
    password: ${PG_PACYORKY_PASS}
    url: ${DB_PACYORKY_HOST}
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false
appId: ${APPID}
appSecret: ${APPSECRET}
updateSecret: ${UPDATE_KEY}
server:
  port: ${PORT:8080}