spring:
  mail:
    host: pacyorky.ee
    port: 587
    username: no-reply@pacyorky.ee
    password: xD7bS7vXhIXkdJdI

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PG_PACYORKY_USER:postgres}
    password: ${PG_PACYORKY_PASS:new_password}
    url: ${DB_PACYORKY_HOST:jdbc:postgresql://localhost:5432/pacyorky}
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
appId: ${APPID:566159457374869}
appSecret: ${APPSECRET:e182c657f48495730f6f712f8fbcbdb6}
updateSecret: ${UPDATE_KEY:0}
server:
  port: ${PORT:3000}