spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: new_password
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false
appId: 566159457374869
appSecret: e182c657f48495730f6f712f8fbcbdb6
updateSecret: gabbagabbahey
server:
  port: ${PORT:3000}