spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PG_PACYORKY_USER:root}
    password: ${PG_PACYORKY_PASS:toor}
    url: ${DB_PACYORKY_HOST:jdbc:postgresql://localhost:5432/pacyorky}
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false
appId: ${APPID}
appSecret: ${APPSECRET}
updateSecret: ${UPDATE_KEY:0}
server:
  port: ${PORT:3000}